### ISSUE TITLE
Milestone 1 - Issues/User Stories

### ISSUE THREAD

**Issue by MalonHolmes** [DSU-Mobile-Computing-Spring-2020/LilArcadeProject#1]
- [x] Create database via Parse
- [x] User Login/Logout/Sign Up
- [x] TabView Controller (Settings, Profile, Home/GameRoom)
- [x] Home Feed Screen (Just the design)
- [x] Settings Screen
- [x] Profile Screen
- [x] Test Database w/ fake user
